-- CreateTable
CREATE TABLE `Peoples` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `totalsUp` BIGINT NOT NULL DEFAULT 0,
    `totalsDown` BIGINT NOT NULL DEFAULT 0,
    `totals` JSON NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
